# Generated by Django 5.0.14 on 2026-01-30 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0006_add_changes_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("new_appointment", "Nouveau rendez-vous"),
                            ("appointment_confirmed", "Rendez-vous confirmé"),
                            ("appointment_rejected", "Rendez-vous refusé"),
                            ("appointment_cancelled", "Rendez-vous annulé"),
                            ("appointment_modified", "Rendez-vous modifié"),
                            ("counter_proposal", "Contre-proposition"),
                            ("proposal_accepted", "Proposition acceptée"),
                            ("proposal_rejected", "Proposition rejetée"),
                            ("appointment_reminder", "Rappel de rendez-vous"),
                            ("system", "Notification système"),
                        ],
                        help_text="Type de notification",
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titre court de la notification",
                        max_length=200,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Message détaillé de la notification",
                        verbose_name="Message",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'icône Lucide React (auto-généré si vide)",
                        max_length=50,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Couleur de la notification (auto-générée si vide)",
                        max_length=20,
                        verbose_name="Couleur",
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL de redirection au clic (ex: /admin/appointments/123)",
                        max_length=500,
                        verbose_name="URL d'action",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="La notification a été lue",
                        verbose_name="Lu",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure de lecture",
                        null=True,
                        verbose_name="Lu le",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "related_appointment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rendez-vous concerné par la notification",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="appointments.appointment",
                        verbose_name="Rendez-vous lié",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utilisateur qui reçoit la notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_611c58_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_a4dd5c_idx",
                    ),
                    models.Index(fields=["type"], name="notificatio_type_8a8a78_idx"),
                ],
            },
        ),
    ]
