# Generated by Django 5.0.14 on 2026-01-20 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_first_name",
                    models.CharField(max_length=100, verbose_name="prénom"),
                ),
                (
                    "patient_last_name",
                    models.CharField(max_length=100, verbose_name="nom"),
                ),
                (
                    "patient_email",
                    models.EmailField(max_length=254, verbose_name="email"),
                ),
                (
                    "patient_phone",
                    models.CharField(max_length=20, verbose_name="téléphone"),
                ),
                ("date", models.DateField(verbose_name="date")),
                ("time", models.TimeField(verbose_name="heure")),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("generale", "Consultation générale"),
                            ("specialisee", "Consultation spécialisée"),
                            ("suivi", "Consultation de suivi"),
                            ("urgence", "Urgence"),
                        ],
                        default="generale",
                        max_length=20,
                        verbose_name="type de consultation",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="motif")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmé"),
                            ("cancelled", "Annulé"),
                            ("completed", "Terminé"),
                            ("no_show", "Absent"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "notes_patient",
                    models.TextField(blank=True, verbose_name="notes patient"),
                ),
                (
                    "notes_staff",
                    models.TextField(blank=True, verbose_name="notes internes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="raison annulation"),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "rendez-vous",
                "verbose_name_plural": "rendez-vous",
                "ordering": ["date", "time"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentSlotLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("locked_by", models.CharField(max_length=100)),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "verrouillage créneau",
                "verbose_name_plural": "verrouillages créneaux",
                "unique_together": {("date", "time")},
            },
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "confirmed"])),
                fields=("date", "time"),
                name="unique_active_appointment_slot",
            ),
        ),
    ]
