# Generated by Django 5.0.14 on 2026-01-23 13:48

import apps.appointments.models
import apps.users.phone_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(
                validators=[apps.appointments.models.validate_appointment_date],
                verbose_name="date",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient_phone",
            field=models.CharField(
                max_length=20,
                validators=[apps.users.phone_validators.validate_congo_phone],
                verbose_name="téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.TimeField(
                validators=[apps.appointments.models.validate_appointment_time],
                verbose_name="heure",
            ),
        ),
    ]
