# Generated by Django 5.0.14 on 2026-01-28 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_appointment_appointment_date_397cae_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("created", "Créé"),
                            ("confirmed", "Confirmé"),
                            ("rejected", "Refusé"),
                            ("proposal_sent", "Proposition envoyée"),
                            ("proposal_accepted", "Proposition acceptée"),
                            ("proposal_rejected", "Proposition refusée"),
                            ("counter_proposed", "Contre-proposition"),
                            ("modified", "Modifié"),
                            ("cancelled", "Annulé"),
                            ("completed", "Terminé"),
                            ("no_show", "Absent"),
                        ],
                        max_length=30,
                        verbose_name="type d'action",
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("patient", "Patient"),
                            ("admin", "Admin"),
                            ("system", "Système"),
                        ],
                        max_length=20,
                        verbose_name="type d'acteur",
                    ),
                ),
                ("old_date", models.DateField(blank=True, null=True)),
                ("old_time", models.TimeField(blank=True, null=True)),
                ("old_consultation_type", models.CharField(blank=True, max_length=20)),
                ("old_status", models.CharField(blank=True, max_length=30)),
                ("new_date", models.DateField(blank=True, null=True)),
                ("new_time", models.TimeField(blank=True, null=True)),
                ("new_consultation_type", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(blank=True, max_length=30)),
                ("message", models.TextField(blank=True, verbose_name="message")),
                ("reason", models.TextField(blank=True, verbose_name="raison")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "historique rendez-vous",
                "verbose_name_plural": "historiques rendez-vous",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposal_type",
                    models.CharField(
                        choices=[
                            ("admin_to_patient", "Admin vers Patient"),
                            ("patient_to_admin", "Patient vers Admin"),
                        ],
                        max_length=20,
                        verbose_name="type de proposition",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("rejected", "Refusée"),
                            ("expired", "Expirée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                ("proposed_date", models.DateField(verbose_name="date proposée")),
                ("proposed_time", models.TimeField(verbose_name="heure proposée")),
                (
                    "proposed_consultation_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="type proposé"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response_message",
                    models.TextField(blank=True, verbose_name="message de réponse"),
                ),
            ],
            options={
                "verbose_name": "proposition rendez-vous",
                "verbose_name_plural": "propositions rendez-vous",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_active_appointment_slot",
        ),
        migrations.AddField(
            model_name="appointment",
            name="admin_message",
            field=models.TextField(blank=True, verbose_name="message admin"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_message",
            field=models.TextField(blank=True, verbose_name="message patient"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="proposal_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="proposition envoyée le"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="proposed_consultation_type",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="type proposé"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="proposed_date",
            field=models.DateField(blank=True, null=True, verbose_name="date proposée"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="proposed_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="heure proposée"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="raison du refus"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="responded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="répondu le"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("confirmed", "Confirmé"),
                    ("rejected", "Refusé"),
                    ("awaiting_patient_response", "En attente patient"),
                    ("awaiting_admin_response", "En attente admin"),
                    ("rejected_by_patient", "Refusé par patient"),
                    ("modification_pending", "Modification en attente"),
                    ("cancelled", "Annulé"),
                    ("completed", "Terminé"),
                    ("no_show", "Absent"),
                ],
                default="pending",
                max_length=30,
                verbose_name="statut",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "pending",
                            "confirmed",
                            "awaiting_patient_response",
                            "awaiting_admin_response",
                            "modification_pending",
                        ],
                    )
                ),
                fields=("date", "time"),
                name="unique_active_appointment_slot",
            ),
        ),
        migrations.AddField(
            model_name="appointmenthistory",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointmenthistory",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointmentproposal",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposals",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointmentproposal",
            name="proposed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="appointmenthistory",
            index=models.Index(
                fields=["appointment", "-created_at"],
                name="appointment_appoint_05f35d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentproposal",
            index=models.Index(
                fields=["appointment", "-created_at"],
                name="appointment_appoint_8a90f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentproposal",
            index=models.Index(
                fields=["status", "expires_at"], name="appointment_status_4f7e71_idx"
            ),
        ),
    ]
