# Generated by Django 5.0.14 on 2026-01-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_appointmenthistory_appointmentproposal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="patient_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="email"),
        ),
    ]
