# Generated by Django 5.0.14 on 2026-02-05 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_add_changes_data"),
        (
            "content_management",
            "0013_consultationfee_alter_clinicsetting_fee_general_and_more",
        ),
        ("users", "0006_merge_20260205_1906"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="medical_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="users.medicalrecord",
                verbose_name="Dossier médical",
            ),
        ),
        migrations.CreateModel(
            name="AppointmentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                (
                    "access_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Code d'accès"
                    ),
                ),
                ("preferred_date", models.DateField(verbose_name="Date préférée")),
                (
                    "preferred_time_slot",
                    models.CharField(max_length=50, verbose_name="Créneau horaire"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmé"),
                            ("cancelled", "Annulé"),
                            ("completed", "Terminé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expire le")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_requests",
                        to="content_management.medicalservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de rendez-vous",
                "verbose_name_plural": "Demandes de rendez-vous",
                "ordering": ["-created_at"],
            },
        ),
    ]
