# Generated by Django 5.0.14 on 2026-01-23 13:39

import apps.users.models
import apps.users.phone_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[apps.users.models.validate_avatar],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="emergency_phone",
            field=models.CharField(
                blank=True,
                help_text="Format: 06 XXX XX XX, 05 XXX XX XX, 04 XXX XX XX ou 222 XX XX XX",
                max_length=20,
                validators=[apps.users.phone_validators.validate_congo_phone],
                verbose_name="téléphone urgence",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Format: 06 XXX XX XX, 05 XXX XX XX, 04 XXX XX XX ou 222 XX XX XX",
                max_length=20,
                validators=[apps.users.phone_validators.validate_congo_phone],
                verbose_name="téléphone",
            ),
        ),
    ]
