# Generated by Django 5.0.14 on 2026-01-23 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0003_user_users_user_email_6f2530_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        help_text="Email/username utilisé",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, help_text="Adresse IP"),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="User-Agent", max_length=500
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Tentative réussie ou non",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, help_text="Raison de l'échec", max_length=255
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Tentative de connexion",
                "verbose_name_plural": "Tentatives de connexion",
                "db_table": "login_attempt",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="login_attem_timesta_ae2617_idx"
                    ),
                    models.Index(
                        fields=["username", "-timestamp"],
                        name="login_attem_usernam_769d7f_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="login_attem_ip_addr_26064e_idx",
                    ),
                    models.Index(
                        fields=["success", "-timestamp"],
                        name="login_attem_success_bb444f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Nom d'utilisateur (conservé même si user supprimé)",
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("register", "Inscription"),
                            ("password_change", "Changement de mot de passe"),
                            ("password_reset", "Réinitialisation de mot de passe"),
                            ("email_verify", "Vérification email"),
                            ("create", "Création"),
                            ("read", "Lecture"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("appointment_create", "Création de RDV"),
                            ("appointment_cancel", "Annulation de RDV"),
                            ("appointment_confirm", "Confirmation de RDV"),
                            ("slot_lock", "Verrouillage de créneau"),
                            ("failed_login", "Échec de connexion"),
                            ("permission_denied", "Accès refusé"),
                            ("suspicious_activity", "Activité suspecte"),
                            ("backup", "Backup"),
                            ("restore", "Restauration"),
                            ("config_change", "Changement de configuration"),
                        ],
                        db_index=True,
                        help_text="Type d'action effectuée",
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        help_text="Niveau de gravité",
                        max_length=20,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID de l'objet concerné", null=True
                    ),
                ),
                ("description", models.TextField(help_text="Description de l'action")),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="Détails des changements (avant/après)",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Adresse IP de l'utilisateur", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="User-Agent du navigateur", max_length=500
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, help_text="Chemin de la requête", max_length=500
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True,
                        help_text="Méthode HTTP (GET, POST, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, help_text="Données supplémentaires", null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de l'action",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type d'objet concerné",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant effectué l'action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'audit",
                "verbose_name_plural": "Logs d'audit",
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="audit_log_timesta_8b04a8_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_log_user_id_79f582_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="audit_log_action_cf8063_idx",
                    ),
                    models.Index(
                        fields=["level", "-timestamp"],
                        name="audit_log_level_4d239f_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="audit_log_ip_addr_a51c08_idx",
                    ),
                ],
            },
        ),
    ]
