# Generated by Django 5.0.14 on 2026-01-23 16:38

import apps.users.models_audit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_loginattempt_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(
                blank=True,
                help_text="Détails des changements (avant/après)",
                null=True,
                validators=[apps.users.models_audit.validate_audit_changes_json],
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                help_text="Données supplémentaires",
                null=True,
                validators=[apps.users.models_audit.validate_audit_extra_data_json],
            ),
        ),
    ]
