# Generated by Django 5.0.14 on 2026-02-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_medical_records"),
        ("users", "0005_alter_auditlog_changes_alter_auditlog_extra_data"),
    ]

    operations = []
