# Generated by Django 5.0.14 on 2026-02-05 18:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0007_appointment_medical_record_appointmentrequest"),
        ("users", "0006_merge_20260205_1906"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pathology",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_cim10",
                    models.CharField(
                        help_text="Code selon la classification internationale des maladies",
                        max_length=10,
                        unique=True,
                        verbose_name="Code CIM-10",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de la pathologie"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cornea", "Maladies de la cornée"),
                            ("lens", "Maladies du cristallin"),
                            ("uvea", "Maladies de l'uvée"),
                            ("glaucoma", "Glaucome"),
                            ("retina", "Maladies de la rétine"),
                            ("optic_nerve", "Maladies du nerf optique"),
                            ("orbit", "Maladies de l'orbite"),
                            ("refraction", "Troubles de la réfraction"),
                            ("amblyopia", "Amblyopie"),
                            ("diplopia", "Diplopie"),
                            ("other", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Pathologie",
                "verbose_name_plural": "Pathologies",
                "ordering": ["code_cim10"],
            },
        ),
        migrations.CreateModel(
            name="OcularExamination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "av_od_loin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Échelle Snellen (ex: 10/10)",
                        max_digits=4,
                        null=True,
                        verbose_name="AV OD Loin",
                    ),
                ),
                (
                    "av_og_loin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="AV OG Loin",
                    ),
                ),
                (
                    "av_od_loin_corrected",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="AV OD Loin corrigée",
                    ),
                ),
                (
                    "av_og_loin_corrected",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="AV OG Loin corrigée",
                    ),
                ),
                (
                    "av_od_pres",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Échelle Parinaud (ex: P2)",
                        max_digits=4,
                        null=True,
                        verbose_name="AV OD Près",
                    ),
                ),
                (
                    "av_og_pres",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="AV OG Près",
                    ),
                ),
                (
                    "av_od_pres_corrected",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="AV OD Près corrigée",
                    ),
                ),
                (
                    "av_og_pres_corrected",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="AV OG Près corrigée",
                    ),
                ),
                (
                    "refraction_od_sphere",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="En dioptries (ex: -2.00)",
                        max_digits=5,
                        null=True,
                        verbose_name="Réfraction OD Sphère",
                    ),
                ),
                (
                    "refraction_od_cylindre",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Réfraction OD Cylindre",
                    ),
                ),
                (
                    "refraction_od_axis",
                    models.IntegerField(
                        blank=True,
                        help_text="En degrés (0-180)",
                        null=True,
                        verbose_name="Réfraction OD Axe",
                    ),
                ),
                (
                    "refraction_og_sphere",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Réfraction OG Sphère",
                    ),
                ),
                (
                    "refraction_og_cylindre",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Réfraction OG Cylindre",
                    ),
                ),
                (
                    "refraction_og_axis",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Réfraction OG Axe"
                    ),
                ),
                (
                    "iop_od",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="En mmHg (valeur normale: 10-21)",
                        max_digits=5,
                        null=True,
                        verbose_name="IOP OD",
                    ),
                ),
                (
                    "iop_og",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="IOP OG",
                    ),
                ),
                (
                    "iop_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("applanation", "Tonométrie à applanation"),
                            ("indentation", "Tonométrie par indentation"),
                            ("air_puff", "Tonométrie à jet d'air"),
                            ("icare", "Tonomètre ICare"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Méthode de mesure",
                    ),
                ),
                (
                    "biomicroscopy_od",
                    models.TextField(
                        blank=True, null=True, verbose_name="Biomicroscopie OD"
                    ),
                ),
                (
                    "biomicroscopy_og",
                    models.TextField(
                        blank=True, null=True, verbose_name="Biomicroscopie OG"
                    ),
                ),
                (
                    "fundus_od",
                    models.TextField(
                        blank=True, null=True, verbose_name="Fond d'œil OD"
                    ),
                ),
                (
                    "fundus_og",
                    models.TextField(
                        blank=True, null=True, verbose_name="Fond d'œil OG"
                    ),
                ),
                (
                    "stereopsis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normale"),
                            ("reduced", "Réduite"),
                            ("absent", "Absente"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Stéréopsie",
                    ),
                ),
                (
                    "color_vision_od",
                    models.BooleanField(
                        default=False, verbose_name="Anomalie vision couleurs OD"
                    ),
                ),
                (
                    "color_vision_og",
                    models.BooleanField(
                        default=False, verbose_name="Anomalie vision couleurs OG"
                    ),
                ),
                (
                    "motility",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motilité oculaire"
                    ),
                ),
                (
                    "schirmer_od",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="En mm/5min (valeur normale: >10)",
                        max_digits=5,
                        null=True,
                        verbose_name="Schirmer OD",
                    ),
                ),
                (
                    "schirmer_og",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Schirmer OG",
                    ),
                ),
                (
                    "pupillary_reflex_od",
                    models.BooleanField(
                        default=True, verbose_name="Réflexe pupillaire OD normal"
                    ),
                ),
                (
                    "pupillary_reflex_og",
                    models.BooleanField(
                        default=True, verbose_name="Réflexe pupillaire OG normal"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notes additionnelles"
                    ),
                ),
                (
                    "exam_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de l'examen",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "examiner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="examinations_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocular_examinations",
                        to="users.medicalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen ophtalmologique",
                "verbose_name_plural": "Examens ophtalmologiques",
                "ordering": ["-exam_date"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prescription_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Valide jusqu'au"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("is_valid", models.BooleanField(default=True, verbose_name="Valide")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="users.medicalrecord",
                    ),
                ),
                (
                    "prescriber",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordonnance",
                "verbose_name_plural": "Ordonnances",
                "ordering": ["-prescription_date"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(max_length=200, verbose_name="Médicament"),
                ),
                (
                    "dosage",
                    models.CharField(
                        help_text="Ex: 1 goutte 2x/jour",
                        max_length=100,
                        verbose_name="Dosage",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="Ex: 10 jours", max_length=100, verbose_name="Durée"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Instructions"
                    ),
                ),
                (
                    "eye",
                    models.CharField(
                        choices=[
                            ("OD", "Œil Droit"),
                            ("OG", "Œil Gauche"),
                            ("OU", "Les Deux"),
                            ("OS", "Œil Spécifique"),
                        ],
                        default="OU",
                        max_length=10,
                        verbose_name="Œil",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="users.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item d'ordonnance",
                "verbose_name_plural": "Items d'ordonnance",
            },
        ),
        migrations.CreateModel(
            name="MedicalRecordVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="Numéro de version"),
                ),
                (
                    "consultation_date",
                    models.DateField(verbose_name="Date de consultation"),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        help_text="Raison de la visite",
                        verbose_name="Motif de consultation",
                    ),
                ),
                (
                    "history",
                    models.TextField(
                        blank=True,
                        help_text="Antécédents et plainte actuelle",
                        null=True,
                        verbose_name="Interrogatoire",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, null=True, verbose_name="Diagnostic"),
                ),
                (
                    "treatment_plan",
                    models.TextField(
                        blank=True, null=True, verbose_name="Plan de traitement"
                    ),
                ),
                (
                    "exam_findings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Résultats d'examen",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes internes (non visibles au patient)",
                        null=True,
                        verbose_name="Notes privées",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "examiner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="users.medicalrecord",
                    ),
                ),
                (
                    "ocular_examination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="record_versions",
                        to="users.ocularexamination",
                    ),
                ),
                (
                    "pathologies",
                    models.ManyToManyField(
                        blank=True, related_name="record_versions", to="users.pathology"
                    ),
                ),
            ],
            options={
                "verbose_name": "Version du dossier médical",
                "verbose_name_plural": "Versions du dossier médical",
                "ordering": ["-consultation_date"],
                "unique_together": {("medical_record", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=10,
                        verbose_name="Genre",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "first_consultation_date",
                    models.DateField(verbose_name="Date de première consultation"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "appointment_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to="appointments.appointmentrequest",
                        verbose_name="Demande de rendez-vous initiale",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "indexes": [
                    models.Index(fields=["email"], name="users_patie_email_b34b4e_idx"),
                    models.Index(fields=["phone"], name="users_patie_phone_999c70_idx"),
                    models.Index(
                        fields=["user"], name="users_patie_user_id_5efe82_idx"
                    ),
                ],
            },
        ),
    ]
