# Generated by Django 5.0.14 on 2026-01-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(default="Centre Médical VIDA", max_length=100),
                ),
                (
                    "address",
                    models.TextField(
                        default="08 Bis rue Mboko, Moungali, Croisement Lénine - Maya-Maya, Brazzaville"
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(default="06 693 47 35", max_length=20),
                ),
                (
                    "phone_secondary",
                    models.CharField(default="05 745 36 88", max_length=20),
                ),
                ("whatsapp", models.CharField(default="242066934735", max_length=20)),
                (
                    "email",
                    models.EmailField(
                        default="centremedvida@gmail.com", max_length=254
                    ),
                ),
                (
                    "fee_general",
                    models.DecimalField(decimal_places=0, default=15000, max_digits=10),
                ),
                (
                    "fee_specialized",
                    models.DecimalField(decimal_places=0, default=25000, max_digits=10),
                ),
                (
                    "opening_hours",
                    models.JSONField(
                        default=dict,
                        help_text="Ex: {'lun-ven': '08h30 - 17h00', 'sam': '08h00 - 12h30'}",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre de la Clinique",
                "verbose_name_plural": "Paramètres de la Clinique",
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField()),
                ("image", models.ImageField(upload_to="hero/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Slide Hero",
                "verbose_name_plural": "Slides Hero",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MedicalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(
                        help_text="Courte description pour la carte", max_length=255
                    ),
                ),
                (
                    "details",
                    models.TextField(help_text="Description complète pour le dropdown"),
                ),
                ("image", models.ImageField(upload_to="services/")),
                (
                    "icon_name",
                    models.CharField(
                        help_text="Nom de l'icône Lucide (ex: Stethoscope)",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Service Médical",
                "verbose_name_plural": "Services Médicaux",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("whatsapp", "WhatsApp"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Lien Social",
                "verbose_name_plural": "Liens Sociaux",
            },
        ),
    ]
