# Generated by Django 5.0.14 on 2026-01-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0002_faq"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sociallink",
            options={
                "ordering": ["order"],
                "verbose_name": "Lien Social",
                "verbose_name_plural": "Liens Sociaux",
            },
        ),
        migrations.AddField(
            model_name="sociallink",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
