# Generated by Django 5.0.14 on 2026-01-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0003_alter_sociallink_options_sociallink_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsetting",
            name="about_text",
            field=models.TextField(
                blank=True, help_text="Texte de présentation de la clinique"
            ),
        ),
        migrations.AddField(
            model_name="clinicsetting",
            name="niu",
            field=models.CharField(blank=True, default="M2300009961883", max_length=50),
        ),
        migrations.AddField(
            model_name="clinicsetting",
            name="rccm",
            field=models.CharField(blank=True, default="B13-0506", max_length=50),
        ),
    ]
