# Generated by Django 5.0.14 on 2026-01-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_management",
            "0004_clinicsetting_about_text_clinicsetting_niu_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=100)),
                (
                    "value",
                    models.CharField(help_text="Ex: 10 000+, 3+, etc.", max_length=20),
                ),
                (
                    "icon_name",
                    models.CharField(help_text="Nom de l'icône Lucide", max_length=50),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Statistique",
                "verbose_name_plural": "Statistiques",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Patient, Consultant, etc.",
                        max_length=100,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(default=5, help_text="Note sur 5"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="heroslide",
            name="cta_link",
            field=models.CharField(
                blank=True,
                help_text="Lien du bouton (ex: #services ou /rdv)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="cta_text",
            field=models.CharField(
                blank=True, help_text="Texte du bouton (optionnel)", max_length=50
            ),
        ),
    ]
