# Generated by Django 5.0.14 on 2026-01-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_management",
            "0005_statistic_testimonial_heroslide_cta_link_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Statistic",
        ),
        migrations.DeleteModel(
            name="Testimonial",
        ),
        migrations.RemoveField(
            model_name="clinicsetting",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="clinicsetting",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="heroslide",
            name="cta_link",
        ),
        migrations.RemoveField(
            model_name="heroslide",
            name="cta_text",
        ),
        migrations.AlterField(
            model_name="clinicsetting",
            name="about_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="clinicsetting",
            name="address",
            field=models.TextField(
                default="08 Bis rue Mboko, Moungali, Brazzaville, Congo"
            ),
        ),
        migrations.AlterField(
            model_name="clinicsetting",
            name="opening_hours",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="clinicsetting",
            name="phone_primary",
            field=models.CharField(default="06 569 12 35", max_length=20),
        ),
        migrations.AlterField(
            model_name="medicalservice",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="medicalservice",
            name="details",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="medicalservice",
            name="icon_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
