# Generated by Django 5.0.14 on 2026-01-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_management",
            "0006_delete_statistic_delete_testimonial_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        unique=True,
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("morning_start", models.TimeField(blank=True, null=True)),
                ("morning_end", models.TimeField(blank=True, null=True)),
                ("afternoon_start", models.TimeField(blank=True, null=True)),
                ("afternoon_end", models.TimeField(blank=True, null=True)),
                (
                    "slot_duration",
                    models.IntegerField(
                        default=30, help_text="Durée créneau en minutes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Horaire",
                "verbose_name_plural": "Horaires",
                "ordering": ["day_of_week"],
            },
        ),
        migrations.CreateModel(
            name="ClinicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, help_text="Se répète chaque année"
                    ),
                ),
            ],
            options={
                "verbose_name": "Jour férié",
                "verbose_name_plural": "Jours fériés",
                "ordering": ["date"],
            },
        ),
    ]
