# Generated by Django 5.0.14 on 2026-01-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0008_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhyVidaReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("icon_name", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Raison de choisir VIDA",
                "verbose_name_plural": "Raisons de choisir VIDA",
                "ordering": ["order"],
            },
        ),
    ]
