# Generated by Django 5.0.14 on 2026-01-23 13:23

import apps.content_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0009_whyvidareason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="image",
            field=models.ImageField(
                upload_to="hero/",
                validators=[apps.content_management.models.validate_content_image],
            ),
        ),
        migrations.AlterField(
            model_name="medicalservice",
            name="image",
            field=models.ImageField(
                upload_to="services/",
                validators=[apps.content_management.models.validate_content_image],
            ),
        ),
    ]
