# Generated by Django 5.0.14 on 2026-01-23 13:39

import apps.content_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0010_alter_heroslide_image_alter_medicalservice_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Format: 06 XXX XX XX, 05 XXX XX XX, 04 XXX XX XX ou 222 XX XX XX",
                max_length=20,
                validators=[apps.content_management.models.validate_contact_phone],
            ),
        ),
    ]
