# Generated by Django 5.0.14 on 2026-01-23 16:38

import apps.content_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0011_alter_contactmessage_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicsetting",
            name="opening_hours",
            field=models.JSONField(
                default=dict,
                validators=[apps.content_management.models.validate_opening_hours_json],
            ),
        ),
    ]
