# Generated by Django 5.0.14 on 2026-01-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0012_alter_clinicsetting_opening_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("generale", "Consultation générale"),
                            ("specialisee", "Consultation spécialisée"),
                            ("suivi", "Consultation de suivi"),
                            ("urgence", "Urgence"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Type de consultation",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Prix en Francs CFA",
                        max_digits=10,
                        verbose_name="Prix (FCFA)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description optionnelle du type de consultation",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Désactiver pour masquer ce type de consultation",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tarif de consultation",
                "verbose_name_plural": "Tarifs des consultations",
                "ordering": ["order", "consultation_type"],
            },
        ),
        migrations.AlterField(
            model_name="clinicsetting",
            name="fee_general",
            field=models.DecimalField(
                decimal_places=0,
                default=15000,
                help_text="DEPRECATED: Utiliser ConsultationFee",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="clinicsetting",
            name="fee_specialized",
            field=models.DecimalField(
                decimal_places=0,
                default=25000,
                help_text="DEPRECATED: Utiliser ConsultationFee",
                max_digits=10,
            ),
        ),
    ]
